name: Compilar APK Android

on:
  push:
    branches: [ main, master, principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: SFyro/action-buildozer@v1.3
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: App-Android-APK
        path: bin/*.apk
